### PR TITLE
add compiler docs and images; couple markdown fixes

### PR DESCRIPTION
**Pull request by dromer**
We can split the `Compiled Mode` docs into separate sections if that works better.
(didn't want to overflow the summary though)

### CODE REVIEW

**Comment by timothyschoen** [comment]
Nice, is this ready for merge?

asking because it goes live as soon as I merge it ;)

**Comment by dromer** [comment]
It can always be improved, but I think the basics are all there.

What do you think about splitting it into separate sections for the SUMMARY overview?
I didn't want to fill it with additional options as there isn't too much info for the rest of the program yet (would be nice if the sections could be collapsed), but as a giant page it might also be a bit overkill.

**Comment by dromer** [comment]
Btw I kept the minimum html bits for styling, since I couldn't see a clear way to do this in plain markdown.
Linters don't like it, but the vscode markdown renderer at least showed things correctly (and arguably it does look a little bit nicer with a touch of style)

**Comment by dromer** [comment]
@timothyschoen I now realized that for the other inline images there are backward slashes used, is there some specific reason for this? I used the normal forward slashes for the file paths, but I didn't know that backward was also possible.

**Comment by dromer** [comment]
I just realized this requires the `create-docs.sh` script to run.

However on my system it complains about the `sed` lines:
```
sed: can't read s/<a href=/<a target="frame" href=/g: No such file or directory
```

**Comment by dromer** [comment]
I think the command should probably be `sed -ix` instead?

**Comment by timothyschoen** [comment]
> @timothyschoen I now realized that for the other inline images there are backward slashes used, is there some specific reason for this? I used the normal forward slashes for the file paths, but I didn't know that backward was also possible.

No idea, we can change this for consistency.

**Comment by timothyschoen** [comment]
I'm merging this into a branch, where I'll add some more documentation before pushing

**Pull request merged**
